name: Test and deploy

on:
- push
- workflow_dispatch

jobs:
  test_and_deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JavaScript
      uses: actions/setup-node@v1
      with:
        node-version: 14.21.3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Install JavaScript dependencies and build
      run: |
        npm install -g bower polymer-cli eslint
        npm install
        bower install
    - name: Run JavaScript tests
      run: |
        polymer test
    - name: Wrap gem and run ruby tests
      run: |
        npm install -g vulcanize
        ./build.sh
        cd gem && ./bin/setup
        bundle exec rake
    - name: Deploy
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
      working-directory: gem
